///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AddProjectModel {
  int? user;
  String? whoAdd;
  String? name;
  String? type;
  String? description;

  AddProjectModel({
    this.user,
    this.whoAdd,
    this.name,
    this.type,
    this.description,
  });
  AddProjectModel.fromJson(Map<String, dynamic> json) {
    user = json['user']?.toInt();
    whoAdd = json['who_add']?.toString();
    name = json['name']?.toString();
    type = json['type']?.toString();
    description = json['description']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user'] = user;
    data['who_add'] = whoAdd;
    data['name'] = name;
    data['type'] = type;
    data['description'] = description;
    return data;
  }
}
