///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MainFaqModel {
  List<FaqModel>? faqModel;
  MainFaqModel({
    this.faqModel,
  });
  static MainFaqModel mainFaqModel = MainFaqModel(
    faqModel: const [],
  );
  MainFaqModel.fromJson(List<dynamic>? jsonList) {
    if (jsonList != null) {
      faqModel = <FaqModel>[];
      jsonList.forEach((v) {
        faqModel!.add(new FaqModel.fromJson(v));
      });
    }
  }
}

class FaqModel {
  int? id;
  String? question;
  String? answer;
  int? author;
  bool? isOpen;

  FaqModel({
    this.id,
    this.question,
    this.answer,
    this.author,
    this.isOpen=false,
  });
  FaqModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    question = json['question']?.toString();
    answer = json['answer']?.toString();
    author = json['author']?.toInt();
    isOpen = false;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['question'] = question;
    data['answer'] = answer;
    data['author'] = author;
    data['is_open'] = isOpen;
    return data;
  }
}