///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OrderModelResults {

  int? id;
  int? author;
  String? authorName;
  int? category;
  int? project;
  String? title;
  String? description;
  String? price;
  String? createdAt;
  String? modifiedAt;

  OrderModelResults({
    this.id,
    this.author,
    this.authorName,
    this.category,
    this.project,
    this.title,
    this.description,
    this.price,
    this.createdAt,
    this.modifiedAt,
  });
  OrderModelResults.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    author = json['author']?.toInt();
    authorName = json['author_name']?.toString();
    category = json['category']?.toInt();
    project = json['project']?.toInt();
    title = json['title']?.toString();
    description = json['description']?.toString();
    price = json['price']?.toString();
    createdAt = json['created_at']?.toString();
    modifiedAt = json['modified_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['author'] = author;
    data['author_name'] = authorName;
    data['category'] = category;
    data['project'] = project;
    data['title'] = title;
    data['description'] = description;
    data['price'] = price;
    data['created_at'] = createdAt;
    data['modified_at'] = modifiedAt;
    return data;
  }
}

class OrderModelLinks {
  String? next;
  String? previous;

  OrderModelLinks({
    this.next,
    this.previous,
  });
  OrderModelLinks.fromJson(Map<String, dynamic> json) {
    next = json['next']?.toString();
    previous = json['previous']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['next'] = next;
    data['previous'] = previous;
    return data;
  }
}

class OrderModel {
  OrderModelLinks? links;
  int? currentPageNumber;
  int? totalPages;
  int? count;
  List<OrderModelResults>? results;

  OrderModel({
    this.links,
    this.currentPageNumber,
    this.totalPages,
    this.count,
    this.results,
  });
  OrderModel.fromJson(Map<String, dynamic> json) {
    links = (json['links'] != null) ? OrderModelLinks.fromJson(json['links']) : null;
    currentPageNumber = json['current_page_number']?.toInt();
    totalPages = json['total_pages']?.toInt();
    count = json['count']?.toInt();
    if (json['results'] != null) {
      final v = json['results'];
      final arr0 = <OrderModelResults>[];
      v.forEach((v) {
        arr0.add(OrderModelResults.fromJson(v));
      });
      results = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (links != null) {
      data['links'] = links!.toJson();
    }
    data['current_page_number'] = currentPageNumber;
    data['total_pages'] = totalPages;
    data['count'] = count;
    if (results != null) {
      final v = results;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v.toJson());
      });
      data['results'] = arr0;
    }
    return data;
  }
}
