///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OrderModelResultsProject {

  int? id;
  String? title;

  OrderModelResultsProject({
    this.id,
    this.title,
  });
  OrderModelResultsProject.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    return data;
  }
}

class OrderModelResultsCategory {

  int? id;
  String? title;

  OrderModelResultsCategory({
    this.id,
    this.title,
  });
  OrderModelResultsCategory.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    return data;
  }
}

class OrderModelResultsAuthor {


  int? id;
  String? firstName;
  String? lastName;
  String? photo;

  OrderModelResultsAuthor({
    this.id,
    this.firstName,
    this.lastName,
    this.photo,
  });
  OrderModelResultsAuthor.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    firstName = json['first_name']?.toString();
    lastName = json['last_name']?.toString();
    photo = json['photo']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['photo'] = photo;
    return data;
  }
}

class OrderModelResults {

  int? id;
  OrderModelResultsAuthor? author;
  String? authorImage;
  String? productImage;
  OrderModelResultsCategory? category;
  OrderModelResultsProject? project;
  String? title;
  String? description;
  String? price;
  String? deliveryTime;
  bool? isClick;

  OrderModelResults({
    this.id,
    this.author,
    this.authorImage,
    this.productImage,
    this.category,
    this.project,
    this.title,
    this.description,
    this.price,
    this.deliveryTime,
    this.isClick=true,
  });
  OrderModelResults.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    author = (json['author'] != null) ? OrderModelResultsAuthor.fromJson(json['author']) : null;
    authorImage = json['author_image']?.toString();
    productImage = json['product_image']?.toString();
    category = (json['category'] != null) ? OrderModelResultsCategory.fromJson(json['category']) : null;
    project = (json['project'] != null) ? OrderModelResultsProject.fromJson(json['project']) : null;
    title = json['title']?.toString();
    description = json['description']?.toString();
    price = json['price']?.toString();
    deliveryTime = json['delivery_time']?.toString();
    isClick=true;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (author != null) {
      data['author'] = author!.toJson();
    }
    data['author_image'] = authorImage;
    data['product_image'] = productImage;
    if (category != null) {
      data['category'] = category!.toJson();
    }
    if (project != null) {
      data['project'] = project!.toJson();
    }
    data['title'] = title;
    data['description'] = description;
    data['price'] = price;
    data['delivery_time'] = deliveryTime;
    data['is_click'] = isClick;
    return data;
  }
}

class OrderModelLinks {

  String? next;
  String? previous;

  OrderModelLinks({
    this.next,
    this.previous,
  });
  OrderModelLinks.fromJson(Map<String, dynamic> json) {
    next = json['next']?.toString();
    previous = json['previous']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['next'] = next;
    data['previous'] = previous;
    return data;
  }
}

class OrderModel {
  OrderModelLinks? links;
  int? currentPageNumber;
  int? totalPages;
  int? count;
  List<OrderModelResults>? results;

  OrderModel({
    this.links,
    this.currentPageNumber,
    this.totalPages,
    this.count,
    this.results,
  });
  OrderModel.fromJson(Map<String, dynamic> json) {
    links = (json['links'] != null) ? OrderModelLinks.fromJson(json['links']) : null;
    currentPageNumber = json['current_page_number']?.toInt();
    totalPages = json['total_pages']?.toInt();
    count = json['count']?.toInt();
    if (json['results'] != null) {
      final v = json['results'];
      final arr0 = <OrderModelResults>[];
      v.forEach((v) {
        arr0.add(OrderModelResults.fromJson(v));
      });
      results = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (links != null) {
      data['links'] = links!.toJson();
    }
    data['current_page_number'] = currentPageNumber;
    data['total_pages'] = totalPages;
    data['count'] = count;
    if (results != null) {
      final v = results;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v.toJson());
      });
      data['results'] = arr0;
    }
    return data;
  }
}
