
///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OrganizationModelResultsFounder {

  int? id;
  String? firstName;
  String? lastName;
  String? photo;

  OrganizationModelResultsFounder({
    this.id,
    this.firstName,
    this.lastName,
    this.photo,
  });
  OrganizationModelResultsFounder.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    firstName = json['first_name']?.toString();
    lastName = json['last_name']?.toString();
    photo = json['photo']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['photo'] = photo;
    return data;
  }
}

class OrganizationModelResults {

  int? id;
  OrganizationModelResultsFounder? founder;
  String? founderImage;
  String? name;
  String? description;
  String? logo;
  String? createdAt;

  OrganizationModelResults({
    this.id,
    this.founder,
    this.founderImage,
    this.name,
    this.description,
    this.logo,
    this.createdAt,
  });
  OrganizationModelResults.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    founder = (json['founder'] != null) ? OrganizationModelResultsFounder.fromJson(json['founder']) : null;
    founderImage = json['founder_image']?.toString();
    name = json['name']?.toString();
    description = json['description']?.toString();
    logo = json['logo']?.toString();
    createdAt = json['created_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (founder != null) {
      data['founder'] = founder!.toJson();
    }
    data['founder_image'] = founderImage;
    data['name'] = name;
    data['description'] = description;
    data['logo'] = logo;
    data['created_at'] = createdAt;
    return data;
  }
}

class OrganizationModelLinks {

  String? next;
  String? previous;

  OrganizationModelLinks({
    this.next,
    this.previous,
  });
  OrganizationModelLinks.fromJson(Map<String, dynamic> json) {
    next = json['next']?.toString();
    previous = json['previous']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['next'] = next;
    data['previous'] = previous;
    return data;
  }
}

class OrganizationModel {

  OrganizationModelLinks? links;
  int? currentPageNumber;
  int? totalPages;
  int? count;
  List<OrganizationModelResults>? results;

  OrganizationModel({
    this.links,
    this.currentPageNumber,
    this.totalPages,
    this.count,
    this.results,
  });
  OrganizationModel.fromJson(Map<String, dynamic> json) {
    links = (json['links'] != null) ? OrganizationModelLinks.fromJson(json['links']) : null;
    currentPageNumber = json['current_page_number']?.toInt();
    totalPages = json['total_pages']?.toInt();
    count = json['count']?.toInt();
    if (json['results'] != null) {
      final v = json['results'];
      final arr0 = <OrganizationModelResults>[];
      v.forEach((v) {
        arr0.add(OrganizationModelResults.fromJson(v));
      });
      results = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (links != null) {
      data['links'] = links!.toJson();
    }
    data['current_page_number'] = currentPageNumber;
    data['total_pages'] = totalPages;
    data['count'] = count;
    if (results != null) {
      final v = results;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v.toJson());
      });
      data['results'] = arr0;
    }
    return data;
  }
}
