///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProjectsModelResultsOwner {

  int? id;
  String? firstName;
  String? lastName;
  String? photo;

  ProjectsModelResultsOwner({
    this.id,
    this.firstName,
    this.lastName,
    this.photo,
  });
  ProjectsModelResultsOwner.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    firstName = json['first_name']?.toString();
    lastName = json['last_name']?.toString();
    photo = json['photo']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['photo'] = photo;
    return data;
  }
}

class ProjectsModelResults {

  int? id;
  ProjectsModelResultsOwner? owner;
  String? type;
  String? title;
  String? helpType;
  String? organization;
  String? deadline;
  String? cover;
  String? coverUrl;
  int? category;
  int? person;
  int? amountCollected;
  int? percent;
  String? cardNumber;
  int? requiredFund;
  String? address;
  String? createdAt;
  String? modifiedAt;

  ProjectsModelResults({
    this.id,
    this.owner,
    this.type,
    this.title,
    this.helpType,
    this.organization,
    this.deadline,
    this.cover,
    this.coverUrl,
    this.category,
    this.person,
    this.amountCollected,
    this.percent,
    this.cardNumber,
    this.requiredFund,
    this.address,
    this.createdAt,
    this.modifiedAt,
  });
  ProjectsModelResults.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    owner = (json['owner'] != null) ? ProjectsModelResultsOwner.fromJson(json['owner']) : null;
    type = json['type']?.toString();
    title = json['title']?.toString();
    helpType = json['help_type']?.toString();
    organization = json['organization']?.toString();
    deadline = json['deadline']?.toString();
    cover = json['cover']?.toString();
    coverUrl = json['cover_url']?.toString();
    category = json['category']?.toInt();
    person = json['person']?.toInt();
    amountCollected = json['amount_collected']?.toInt();
    percent = json['percent']?.toInt();
    cardNumber = json['card_number']?.toString();
    requiredFund = json['required_fund']?.toInt();
    address = json['address']?.toString();
    createdAt = json['created_at']?.toString();
    modifiedAt = json['modified_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (owner != null) {
      data['owner'] = owner!.toJson();
    }
    data['type'] = type;
    data['title'] = title;
    data['help_type'] = helpType;
    data['organization'] = organization;
    data['deadline'] = deadline;
    data['cover'] = cover;
    data['cover_url'] = coverUrl;
    data['category'] = category;
    data['person'] = person;
    data['amount_collected'] = amountCollected;
    data['percent'] = percent;
    data['card_number'] = cardNumber;
    data['required_fund'] = requiredFund;
    data['address'] = address;
    data['created_at'] = createdAt;
    data['modified_at'] = modifiedAt;
    return data;
  }
}

class ProjectsModelLinks {

  String? next;
  String? previous;

  ProjectsModelLinks({
    this.next,
    this.previous,
  });
  ProjectsModelLinks.fromJson(Map<String, dynamic> json) {
    next = json['next']?.toString();
    previous = json['previous']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['next'] = next;
    data['previous'] = previous;
    return data;
  }
}

class ProjectsModel {

  ProjectsModelLinks? links;
  int? currentPageNumber;
  int? totalPages;
  int? count;
  List<ProjectsModelResults>? results;

  ProjectsModel({
    this.links,
    this.currentPageNumber,
    this.totalPages,
    this.count,
    this.results,
  });
  ProjectsModel.fromJson(Map<String, dynamic> json) {
    links = (json['links'] != null) ? ProjectsModelLinks.fromJson(json['links']) : null;
    currentPageNumber = json['current_page_number']?.toInt();
    totalPages = json['total_pages']?.toInt();
    count = json['count']?.toInt();
    if (json['results'] != null) {
      final v = json['results'];
      final arr0 = <ProjectsModelResults>[];
      v.forEach((v) {
        arr0.add(ProjectsModelResults.fromJson(v));
      });
      results = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (links != null) {
      data['links'] = links!.toJson();
    }
    data['current_page_number'] = currentPageNumber;
    data['total_pages'] = totalPages;
    data['count'] = count;
    if (results != null) {
      final v = results;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v.toJson());
      });
      data['results'] = arr0;
    }
    return data;
  }
}
