import 'package:equatable/equatable.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
///
class MainRuleModel extends Equatable {
  List<RulePageModel>? ruleModel;

  MainRuleModel({
    this.ruleModel,
  });

  static MainRuleModel mainFaqModel = MainRuleModel(
    ruleModel: const [],
  );

  MainRuleModel.fromJson(List<dynamic>? jsonList) {
    if (jsonList != null) {
      ruleModel = <RulePageModel>[];
      jsonList.forEach((v) {
        ruleModel!.add(new RulePageModel.fromJson(v));
      });
    }
  }

  @override
  // TODO: implement props
  List<Object?> get props => [ruleModel];
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
          other is MainRuleModel &&
              runtimeType == other.runtimeType &&
              ruleModel == other.ruleModel;

}

class RulePageModel {

  int? id;
  String? title;
  int? orderNumber;
  String? content;

  RulePageModel({
    this.id,
    this.title,
    this.orderNumber,
    this.content,
  });
  RulePageModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    orderNumber = json['order_number']?.toInt();
    content = json['content']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['order_number'] = orderNumber;
    data['content'] = content;
    return data;
  }
}
