///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class VolunteerDonateResultsProject {
  int? id;
  String? title;

  VolunteerDonateResultsProject({
    this.id,
    this.title,
  });
  VolunteerDonateResultsProject.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    return data;
  }
}

class VolunteerDonateResultsUser {

  int? id;
  String? firstName;
  String? lastName;
  String? photo;

  VolunteerDonateResultsUser({
    this.id,
    this.firstName,
    this.lastName,
    this.photo,
  });
  VolunteerDonateResultsUser.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    firstName = json['first_name']?.toString();
    lastName = json['last_name']?.toString();
    photo = json['photo']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['photo'] = photo;
    return data;
  }
}

class VolunteerDonateResults {

  int? id;
  VolunteerDonateResultsUser? user;
  VolunteerDonateResultsProject? project;
  String? executionTime;
  String? status;

  VolunteerDonateResults({
    this.id,
    this.user,
    this.project,
    this.executionTime,
    this.status,
  });
  VolunteerDonateResults.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    user = (json['user'] != null) ? VolunteerDonateResultsUser.fromJson(json['user']) : null;
    project = (json['project'] != null) ? VolunteerDonateResultsProject.fromJson(json['project']) : null;
    executionTime = json['execution_time']?.toString();
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (user != null) {
      data['user'] = user!.toJson();
    }
    if (project != null) {
      data['project'] = project!.toJson();
    }
    data['execution_time'] = executionTime;
    data['status'] = status;
    return data;
  }
}

class VolunteerDonateLinks {

  String? next;
  String? previous;

  VolunteerDonateLinks({
    this.next,
    this.previous,
  });
  VolunteerDonateLinks.fromJson(Map<String, dynamic> json) {
    next = json['next']?.toString();
    previous = json['previous']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['next'] = next;
    data['previous'] = previous;
    return data;
  }
}

class VolunteerDonate {

  VolunteerDonateLinks? links;
  int? currentPageNumber;
  int? totalPages;
  int? count;
  List<VolunteerDonateResults?>? results;

  VolunteerDonate({
    this.links,
    this.currentPageNumber,
    this.totalPages,
    this.count,
    this.results,
  });
  VolunteerDonate.fromJson(Map<String, dynamic> json) {
    links = (json['links'] != null) ? VolunteerDonateLinks.fromJson(json['links']) : null;
    currentPageNumber = json['current_page_number']?.toInt();
    totalPages = json['total_pages']?.toInt();
    count = json['count']?.toInt();
    if (json['results'] != null) {
      final v = json['results'];
      final arr0 = <VolunteerDonateResults>[];
      v.forEach((v) {
        arr0.add(VolunteerDonateResults.fromJson(v));
      });
      results = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (links != null) {
      data['links'] = links!.toJson();
    }
    data['current_page_number'] = currentPageNumber;
    data['total_pages'] = totalPages;
    data['count'] = count;
    if (results != null) {
      final v = results;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['results'] = arr0;
    }
    return data;
  }
}
